import {Platform} from 'react-native';

export default {
    host: 'https://delivery-api.harveynetwork.com',
    baseColor: '#34495E',
    bgColor: '#ECF0F1',
    isIos: Platform.OS === 'ios',
    //bold: 'Roboto',
    txtColor: '#333',
    blackColor: '#000000',
    whiteColor: '#ffffff',
    idToken: 'id_token',
    currency: '$',
    paymentCurrencyCode: 'USD',
    androidPayMode: 'test',
    labelName: 'RagiBull', 
    merchantId: 'merchant.com.deliveryapp.app',  
    stripeSecretKey: 'sk_test_51IOWfdGQlL3ftoEbbRRjQeLXKBEWRX9ZBtZmkeCQ5mbGoh3lbx6QbqfbLpUQeRryDMgVYHkySPnxjAVnxuqQNRxf00oM1u3Gtg',
    publishableKey: 'pk_test_51IOWfdGQlL3ftoEbeRWvgmjcQP0nVIyq3ne8nzukYDIfIXJ68YxszvJk3BCOWHvEVCXfwYWwGtMsX2Y2lHRE6JGi00g39JUUSb',
    xShard: 'Raus',
    locationBaseUrl: "https://maps.googleapis.com/maps/api/place/autocomplete/json",
    google_key: "AIzaSyDIwggD-DXUmXaU462dwrzGpZ75y8VEOP8",
    geoCodeBaseUrl: "https://maps.googleapis.com/maps/api/geocode/json",
    appleIdMessage: 'You must share your email address to login with the apple Id',
    forgotScreenTitle: 'Forgot Password',
    forgotScreenCaption: 'Please enter your Information below in order to login to you Account',
    otpScreenCaption: 'Enter the 6 digit code sent to your registered Email address.',
    otpScreenTitle: 'OTP Verification',
    resetPasswordScreenCaption: 'Enter your new password atleast 6 digit long.',
    resetPasswordScreenTitle: 'Reset Password',
    applicationFees: 'Application fees',
    deliveryFees:"Delivery fees",
    tax: "Tax",
    subTotal: 'Subtotal',
    notificationRegisterPost:"https://delivery-api.harveynetwork.com/api/customer-notification/register",
    applicationFeesPost:"https://delivery-api.harveynetwork.com/api/order/get-application-fees"
}